steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-app-demo/flask_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-app-demo/flask_app']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'SERVICE_NAME',
    '--image', 'DOCKER_REPOSITORY/IMAGE_NAME',
    '--region', 'REGION']
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/flask-app-demo/flask_app'